management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

# reduce severity of logging noise when running in compose
logging:
  level:
    root: INFO
